"""
This file contains the locators for the 'Documents' page of the application.
Locators are used by the Robot Framework tests to interact with elements on the web page.
"""
BrowseFileInDocuments= "xpath=//input[@type='file']"
UploadButton= "xpath=//button[normalize-space()='Upload']"
Claims = "xpath=//a[normalize-space()='Claims']"
DownloadDropdown = "xpath=//button[normalize-space()='Download']"
DownloadData = "xpath=//a[normalize-space()='Download Data']"
Policies = "xpath=//a[normalize-space()='Policies']"
Analysis = "xpath=//a[normalize-space()='Analysis']"
CardDatas1 = "xpath=//dt[text()='"
CardDatas2 = "']//following-sibling::dd"
AnalysisTableData = "xpath=//td//span"
DownloadSchema = "xpath=//ng-transclude[normalize-space()='Download Schema']"
ArchiveButton1 = "xpath=//div[text()='"
ArchiveButton2 = "']/..//button"
Email_Body_Doc="xpath=//a[@data-cy='asset-card-file-EMAIL BODY' or @data-cy='asset-card-file-Great Western Lumber - effective.eml']"
Email_Body_msg="xpath=//div[@ng-bind-html='$ctrl.body']"
underwriter_reference_Doc="xpath=//a[@data-cy='asset-card-file-Underwriter Reference Lookup']"
Acord_125_loc="xpath=//a[@data-cy='asset-card-file-ACORD 125 (2013/01)']"
Acord_140_loc="xpath=//a[@data-cy='asset-card-file-ACORD 140 (2007/09)']"
Broker_form_loc="xpath=//a[@data-cy='asset-card-file-Broker Form']"
Loss_run_EASTERNALLIANCE="xpath=//a[@data-cy='asset-card-file-Loss Run (EASTERNALLIANCE)']"


underwriter_reference_lookup="xpath=(//span[text()='Code'])//following::span[text()='Underwriter Reference Lookup']"

Document_options = "xpath=//submission-options-button[@test-id='submission-option-button']//button"
Document_Options_Dropdown = "xpath=//submission-options-button[@test-id='submission-option-button']//div//a"
Show_Documents = "xpath=//a[@test-id='submission-options-toggle-system-docs']"
Broker_ref_Lookup = "xpath=//a[@data-cy='assets-files-Broker Reference Lookup']"

Doc_Processed_loc="xpath=(//ng-transclude[contains(normalize-space(), 'Processed')])[2]"
Doc_Archived_loc="xpath=(//ng-transclude[contains(normalize-space(), 'Archived')])[2]"
Doc_External_links_loc="xpath=(//ng-transclude[contains(normalize-space(), 'External Links')])[2]"
Search_file_loc="xpath=//input[@data-cy='assets-search-input']"
Email_body_more_option="xpath=(//button[@test-id='asset-card-options-menu-email_body'])[1]"
Email_body_dowload_option="xpath=//button[@test-id='asset-card-options-download-email_body']"
 
Email_body_info_option="xpath=//button[@test-id='asset-card-options-info-email_body']"
Document_more_options_fields="xpath=//div[@ng-if='$ctrl.menuOpen']//button"
Document_info_detials_field="xpath=(//div[@test-id='asset-card-details-email_body'])[1]//div[@class='font-semibold']"
Document_info_detials_value="xpath=(//div[@test-id='asset-card-details-email_body'])[1]//div[@class='text-gray-500 ng-binding']"
Email_Body_1="xpath=//a[@data-cy='assets-files-"
Docment_delete_option="xpath=//button[@test-id='asset-card-options-delete-email_body']"
Document_Back_button="xpath=//a[text()='BACK']"
more_option="xpath=//button[@test-id='asset-card-options-menu-"
Docment_delete_option1="xpath=//button[@test-id='asset-card-options-delete-"
Archived_document_files="xpath=//button[@test-id='asset-card-options-menu-archived']"
Archived_delete_button="xpath=//button[@test-id='asset-card-options-delete-archived']"
Document_Attachemnt_files="xpath=//assets-files-aside-add-files-email//div[@ng-if and @ng-repeat]//span[contains(@class,'truncate')]"
Attachement_files_archive_buttom="xpath=//assets-files-aside-add-files-email//div[@ng-if and @ng-repeat]//button[@uib-tooltip='Archive']"
Attachement_msg="xpath=//assets-files-aside-add-files-email//div[@class='flex items-center gap-2 mt-2 ng-scope'] //span"
Add_row_button="xpath=//d3-button[@ng-if='$ctrl.editorEnabled()']//ng-transclude"
Loading="xpath=//span[text()='Loading...']"
Sov_options="xpath=(//header)[3]//a"
sov_select_option="xpath=(//header)[3]//a[normalize-space()='"
Sov_addrow="xpath=//ng-transclude[text()='Add Row']"
sov_file_cell="xpath=//tbody//tr//td"
Sov_Driver_option="xpath=(//header)[3]//a[normalize-space()='Drivers']"
Sov_save="xpath=//ng-transclude[text()='Save']"
Cell_input="xpath=//div[@class='handsontableInputHolder ht_clone_master']//textarea"
DocPropertiesColumnSearch="xpath=//input[@placeholder='Search Columns']"

Totol_claims="xpath=//dt[text()='Total Claims']//following-sibling::dd"
claims_button="xpath=//a[normalize-space()='Claims']"