"""
This file contains the locators for the 'Risk360' page of the application.
Locators are used by the Robot Framework tests to interact with elements on the web page.
"""
Side_Bar_Risk360_Button = "xpath=//a[@test-id='risk360nav']"
Risk360_Cards = "xpath=//div[@test-id='ui-card-"
Risk360_Empty_Cards = "xpath=//button//ng-transclude[text()='Empty Cards']"
Risk360_Cards_Pages_Header = "xpath=//*[@test-id='ui-card-template-back-title' and contains(normalize-space(.),'"
Risk360_Cards_Pages_Close_Button = "xpath=//button//ng-transclude[text()='Close']"

NAIC_Delete = "xpath=(//section[@id='industry']//following::button[contains(@test-id,'r360-sidebar-primary-naics-delete-button')])[1]"
NAIC_Reprocess = "xpath=//ng-transclude[normalize-space()='Reprocess']"
Reprocess_Popup = "xpath=//div[@id='toast-container']/div"
Social_media_Link="xpath=//li[@ng-repeat='socialLink in value']//a"
linked_In_profile="xpath=//a[@aria-label='LinkedIn']"

risk_year="xpath=//div[@test-id='r360-established-child']//span"
risk_description="xpath=//d3-source[@test-id='r360-sidebar-description']//following::p"
Resorce_link="xpath=//div[@test-id='r360-sidebar-resource-links']//a"
DescriptionShowAllButton="xpath=//button[@test-id='r360-sidebar-description-show-all']"
AMBest_Row="xpath=//tbody//tr"
Am_bestcard="xpath=//div[@test-id='ui-card-title-AM Best']"
AmCard_setpages="xpath=//select[@ng-change='$ctrl.changePageSize()']" 
Amcard_Nasicscode1="((//tbody//tr)["
Amcard_Nasicscode2="]//td)[3]"
Amcard_Nasicscode3="]//td)[1]"
Hazmat_tooltip="xpath=//div[@content='Not a hazmat carrier']//div[@ng-bind='content']"
Hazmant_remove_icon="xpath=//i[@uib-tooltip='Not a hazmat carrier']"
hazmat_haular_card="xpath=//d3-source[@test-id='app-finding-4']"
